[project]
name = "celery-mongo-rabbitmq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.6.3",
    "celery-types>=0.26.0",
    "flower>=2.0.1",
    "pydantic-settings>=2.15.0",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.2",
]
